2<bind tag="pagename"> SnappleJack: <card/> </bind>5
    <apply template="_cardd"/>
    <apply template="_cardf"/>
    <apply template="_cards"/>
    <apply template="_cardc"/>
    <apply template="_cardh"/>5
     <apply template="_singled"/>
     <apply template="_singlef"/>
     <apply template="_singles"/>
     <apply template="_singlec"/>
     <apply template="_singleh"/>
